site_name: Eblasoft Documentation

site_url: https://docs.eblasoft.com.tr/

repo_url: https://github.com/eblasoft/documentation/
edit_uri: edit/main/docs/

extra_javascript: [ js/extra.js ]

extra_css:
  - css/extra.css

extra:
  analytics:
    provider: google
    property: G-ZBGS3K1JEH

  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/ebla-soft/

  status:
    new: New Extension
    deprecated: Deprecated
    featured: Popular Extension, Recommended

plugins:
  - glightbox
  - search
  #- social
  #- tags

copyright: Copyright &copy; 2016 - 2026 Eblasoft Bili≈üim Ltd.

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.superfences
  - mdx_truly_sane_lists
  - codehilite:
      guess_lang: false
      use_pygments: true
  - toc:
      permalink: true
      toc_depth: 3
      title: On this page
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


theme:
  name: material
  logo: _static/images/docs/white-logo.png
  highlightjs: true
  favicon: _static/images/docs/blue-logo.png
  features:
    # Navigation features
    #- navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    #- navigation.sections
    #- navigation.expand
    #- navigation.path
    - navigation.indexes
    - navigation.prune
    - navigation.top
    - navigation.footer

    - header.autohide

    - search.suggest
    - search.highlight
    - search.share
    - content.action.edit
    #- toc.integrate
    - toc.follow
  icon:
    edit: material/pencil

  palette:
    # Palette toggle for light mode
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: light blue
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: light blue
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

nav:
  - Mobile PWA: 'espocrm-extensions/mobile-app/index.md'
  - Ebla Theme: 'espocrm-extensions/ebla-theme/index.md'
  - Ebla Nav Pro: 'espocrm-extensions/nav-pro/index.md'
  - Ebla Dash Pro: 'espocrm-extensions/dashlet-pro/index.md'
  - Ebla List Pro: 'espocrm-extensions/list-pro/index.md'
  - Ebla Labels: 'espocrm-extensions/labels-cells/index.md'
  - Ebla Switch: 'espocrm-extensions/switch/index.md'
  - Ebla Infinity Scroll: 'espocrm-extensions/infinity-scroll/index.md'
  - Ebla Layout Pro: 'espocrm-extensions/layout-pro/index.md'
  - Ebla Kanban Multiple: 'espocrm-extensions/kanban-multiple/index.md'
  - Ebla Gantt: 'espocrm-extensions/gantt/index.md'

  - Ebla Number Pro: 'espocrm-extensions/number-pro/index.md'
  - Ebla Mask Field: 'espocrm-extensions/mask-field/index.md'
  - Ebla Rate Star Field: 'espocrm-extensions/rate/index.md'
  - Ebla Dynamic Logic Plus: 'espocrm-extensions/dynamic-logic-plus/index.md'
  - Ebla Enum Plus: 'espocrm-extensions/enum-plus/index.md'
  - Ebla Link Pro: 'espocrm-extensions/link-multiple-pro/index.md'
  - Ebla Map Plus: 'espocrm-extensions/map-plus/index.md'
  - Ebla Iframe Field: 'espocrm-extensions/iframe-field/index.md'
  - Ebla Progress Bar: 'espocrm-extensions/progress-bar/index.md'
  - Ebla Date Pro: 'espocrm-extensions/date-pro/index.md'

  - Ebla Public Form: 'espocrm-extensions/public-form/index.md'
  - Ebla Work Log: 'espocrm-extensions/work-log/index.md'
  - Ebla Contract: 'espocrm-extensions/ebla-contract/index.md'
  - Ebla Follow Up: 'espocrm-extensions/ebla-follow-up/index.md'
  - Ebla Quick Assign: 'espocrm-extensions/quick-assign/index.md'
  - Ebla Shared Filter: 'espocrm-extensions/shared-filter/index.md'
  - Ebla Event Plus: 'espocrm-extensions/event-plus/index.md'
  - Ebla Generic Filter: 'espocrm-extensions/generic-filter/index.md'

  - Ebla Chat: 'espocrm-extensions/chat/index.md'
  - Ebla Sms: 'espocrm-extensions/sms/index.md'
  - Ebla Stream Plus: 'espocrm-extensions/stream-plus/index.md'
  - Ebla Reactions: 'espocrm-extensions/reactions/index.md'

  - Ebla AI: 'espocrm-extensions/espocrm-ai/index.md'
  - Ebla Admin Pro: 'espocrm-extensions/admin-pro/index.md'
  - Ebla Print: 'espocrm-extensions/print/index.md'
  - Ebla Category Tree: 'espocrm-extensions/category-tree/index.md'
  - Ebla Last Login: 'espocrm-extensions/last-login/index.md'
  - Ebla Welcome: 'espocrm-extensions/welcome/index.md'

  - Ebla Internal & Public Case: 'espocrm-extensions/internal-public-case/index.md'
